openapi: 3.0.0
info:
  title: Legal Resources API
  version: 1.0.0
paths:
  /musikos/v1/legal/terms:
    get:
      tags:
        - Legal
      summary: Get the terms and conditions data.
      responses:
        '200':
          description: Successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                    example: "67a760a9f54fc89199a6cf9e"
                  type:
                    type: string
                    example: "terms"
                  html:
                    type: string
                    example: "\n<div>Ejemplo de html</div>"
        '500':
          $ref: "#/components/responses/internalServerError"

  /musikos/v1/legal/privacy:
    get:
      tags:
        - Legal
      summary: Get the privacy policy data.
      responses:
        '200':
          description: Successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                    example: "67a760a9f54fc89199a6cf9e"
                  type:
                    type: string
                    example: "privacy"
                  html:
                    type: string
                    example: "\n<div>Ejemplo</div>"
        '500':
          $ref: "#/components/responses/internalServerError"