openapi: 3.0.0
info:
  title: API de recursos legales
  version: 1.0.0
paths:
  /bandbros/v1/legal/terms:
    get:
      tags:
        - Legal
      summary: Obtener los terminos y condiciones.
      responses:
        '200':
          description: Respuesta exitosa.
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                    example: "67a760a9f54fc89199a6cf9e"
                  type:
                    type: string
                    example: "terms"
                  html:
                    type: string
                    example: "\n<div>Ejemplo de html</div>"
        '404':
          description: Error en la solicitud.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                message: "Fallo al obtener los términos y condiciones"
                status: 404
                type: "interno"
        '500':
          $ref: "#/components/responses/UnexpectedError"

  /bandbros/v1/legal/privacy:
    get:
      tags:
        - Legal
      summary: Obtener la política de privacidad.
      responses:
        '200':
          description: Respuesta exitosa.
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                    example: "67a760a9f54fc89199a6cf9e"
                  type:
                    type: string
                    example: "privacy"
                  html:
                    type: string
                    example: "\n<div>Ejemplo</div>"
        '404':
          description: Error en la solicitud.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                message: "Fallo al obtener la política de privacidad"
                type: "interno"
        '500':
          $ref: "#/components/responses/UnexpectedError"