openapi: 3.0.0
info:
  title: Musician actions API
  version: 1.0.0
paths:
  /musikos/v1/musicians/check-email:
    post:
      tags:
        - Musicians
      summary: Check if an email already exists in the database.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "ejemplo@ejemplo.com"
      responses:
        '200':
          description: Successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  exists:
                    type: boolean
                    example: true
        '500':
          $ref: "#/components/responses/internalServerError"
        '400':
          $ref: "#/components/responses/badRequest"
  /musikos/v1/musicians/check-username:
      post:
        tags:
          - Musicians
        summary: Check if a username already exists in the database.
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                    example: "pepito"
        responses:
          '200':
            description: Successful response.
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    exists:
                      type: boolean
                      example: true
          '500':
            $ref: "#/components/responses/internalServerError"
          '400':
            $ref: "#/components/responses/badRequest"

